---
- hosts: all
  roles:
    - base

- name: terraform
  hosts: all
  roles:
    - terraform

- name: output
  hosts: all
  tasks:
    - shell: "ansible --version"
      register: ansiver
    - debug: var=ansiver.stdout_lines
